accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'


urlpatterns = [
    # path('login/', auth_views.LoginView.as_view(), name='login'),
]

ecom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('product.urls')),
    path('product/',include('product.urls'), name='product'),
    path('accounts/',include('django.contrib.auth.urls'), name='accounts'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from . import views

app_name = 'product'


urlpatterns = [
    path('', views.index, name='index'),
    path('list', views.productlist, name='product_list'),
    path('<str:slug>',views.productdetails, name='product_detail')
]

accounts/models.py
from django.db import models

# Create your models here.

product/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.text import slugify


class Category(models.Model):
    category_name = models.CharField(max_length=200)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.category_name

class Brand(models.Model):
    brand_name = models.CharField(max_length=200)

    class Meta:
        verbose_name = 'brand'
        verbose_name_plural = 'brands'

    def __str__(self):
        return self.brand_name




class Product(models.Model):

    CONDITION_TYPE = (
        ("New","New"),
        ("Used","Used")
    )

    title = models.CharField(max_length = 100)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    decrtiption = models.TextField()
    condition = models.CharField(max_length=200, choices=CONDITION_TYPE)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    brand = models.ForeignKey(Brand, on_delete=models.SET_NULL, null=True)
    image = models.ImageField(upload_to="uploads/", blank=True, null=True)
    created = models.DateTimeField(default=timezone.now)

    slug = models.SlugField(blank=True, null=True)

    def save(self, *args, **kwarws):
        if not self.slug and self.title:
            self.slug = slugify(self.title)
        super(Product, self).save(*args, **kwarws)

    def __str__(self):
        return self.title



class ProductImages(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products/", blank=True, null=True)

    class Meta:
        verbose_name = 'Product Image'
        verbose_name_plural = 'Product Images'

    def __str__(self):
        return self.product.title

accounts/views.py
from django.shortcuts import render

# Create your views here.

product/views.py
from django.shortcuts import render
from .models import Product, ProductImages

def productlist(request):
    productlist = Product.objects.all()
    context = {
        'product_list' : productlist
    }
    return render(request, 'product/product_list.html', context)


def productdetails(request, slug):
    productdetails = Product.objects.get(slug=slug)
    productimages = ProductImages.objects.filter(product=productdetails)

    context = {
        'product_details' : productdetails,
        'product_images' : productimages
    }
    return render(request, 'product/product_details.html', context)


def index(request):
    return render(request,'product/index.html')

product/templates/product/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<title>Home</title>
<link rel="stylesheet" href="{% static 'product/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'product/css/bootstrap-select.css'%}">
<link href="{% static 'product/css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
<link rel="stylesheet" href="{% static 'product/css/flexslider.css' %}" type="text/css" media="screen" />
<link rel="stylesheet" href="{% static 'product/css/font-awesome.min.css' %}" />
<!-- for-mobile-apps -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Resale Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- //for-mobile-apps -->
<!--fonts-->
<link href='//fonts.googleapis.com/css?family=Ubuntu+Condensed' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
<!--//fonts-->	
<!-- js -->
<script type="text/javascript" src="{% static 'product/js/jquery.min.js' %}"></script>
<!-- js -->
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="{% static 'product/js/bootstrap.min.js' %}"></script>
<script src="{% static 'product/js/bootstrap-select.js' %}"></script>
<script>
  $(document).ready(function () {
    var mySelect = $('#first-disabled2');

    $('#special').on('click', function () {
      mySelect.find('option:selected').prop('disabled', true);
      mySelect.selectpicker('refresh');
    });

    $('#special2').on('click', function () {
      mySelect.find('option:disabled').prop('disabled', false);
      mySelect.selectpicker('refresh');
    });

    $('#basic2').selectpicker({
      liveSearch: true,
      maxOptions: 1
    });
  });
</script>
<script type="text/javascript" src="{% static 'product/js/jquery.leanModal.min.js' %}"></script>
<link href="{% static 'product/css/jquery.uls.css' %}" rel="stylesheet"/>
<link href="{% static 'product/css/jquery.uls.grid.css' %}" rel="stylesheet"/>
<link href="{% static 'product/css/jquery.uls.lcd.css' %}" rel="stylesheet"/>
<!-- Source -->
<script src="{% static 'product/js/jquery.uls.data.js' %}"></script>
<script src="{% static 'product/js/jquery.uls.data.utils.js' %}"></script>
<script src="{% static 'product/js/jquery.uls.lcd.js' %}"></script>
<script src="{% static 'product/js/jquery.uls.languagefilter.js' %}"></script>
<script src="{% static 'product/js/jquery.uls.regionfilter.js' %}"></script>
<script src="{% static 'product/js/jquery.uls.core.js' %}"></script>
<script>
			$( document ).ready( function() {
				$( '.uls-trigger' ).uls( {
					onSelect : function( language ) {
						var languageName = $.uls.data.getAutonym( language );
						$( '.uls-trigger' ).text( languageName );
					},
					quickList: ['en', 'hi', 'he', 'ml', 'ta', 'fr'] //FIXME
				} );
			} );
		</script>
</head>
<body>
	<div class="header">
		<div class="container">
			<div class="logo">
				<a href="index.html"><span>Re</span>sale</a>
			</div>
			<div class="header-right">
				<a class="account" href="{% url 'product:index' %}">My Account</a>
				<!-- Large modal -->
		
			</div>
		</div>
	</div>
	<div class="main-banner banner text-center">
	  <div class="container">    
			<h1>Sell or Advertise   <span class="segment-heading">    anything online </span> with Resale</h1>
			<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
			<a href="post-ad.html">Post Free Ad</a>
	  </div>
	</div>
		<!-- content-starts-here -->
		{% block body %}

		


		{% endblock body %}
		<!--footer section start-->		
		<footer>
			<div class="footer-top">
				<div class="container">
					<div class="foo-grids">
						<div class="col-md-3 footer-grid">
							<h4 class="footer-head">Who We Are</h4>
							<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
							<p>The point of using Lorem Ipsum is that it has a more-or-less normal letters, as opposed to using 'Content here.</p>
						</div>
						<div class="col-md-3 footer-grid">
							<h4 class="footer-head">Help</h4>
							<ul>
								<li><a href="howitworks.html">How it Works</a></li>						
								<li><a href="sitemap.html">Sitemap</a></li>
								<li><a href="faq.html">Faq</a></li>
								<li><a href="feedback.html">Feedback</a></li>
								<li><a href="contact.html">Contact</a></li>
								<li><a href="typography.html">Shortcodes</a></li>
							</ul>
						</div>
						<div class="col-md-3 footer-grid">
							<h4 class="footer-head">Information</h4>
							<ul>
								<li><a href="regions.html">Locations Map</a></li>	
								<li><a href="terms.html">Terms of Use</a></li>
								<li><a href="popular-search.html">Popular searches</a></li>	
								<li><a href="privacy.html">Privacy Policy</a></li>	
							</ul>
						</div>
						<div class="col-md-3 footer-grid">
							<h4 class="footer-head">Contact Us</h4>
							<span class="hq">Our headquarters</span>
							<address>
								<ul class="location">
									<li><span class="glyphicon glyphicon-map-marker"></span></li>
									<li>CENTER FOR FINANCIAL ASSISTANCE TO DEPOSED NIGERIAN ROYALTY</li>
									<div class="clearfix"></div>
								</ul>	
								<ul class="location">
									<li><span class="glyphicon glyphicon-earphone"></span></li>
									<li>+0 561 111 235</li>
									<div class="clearfix"></div>
								</ul>	
								<ul class="location">
									<li><span class="glyphicon glyphicon-envelope"></span></li>
									<li><a href="mailto:info@example.com">mail@example.com</a></li>
									<div class="clearfix"></div>
								</ul>						
							</address>
						</div>
						<div class="clearfix"></div>
					</div>						
				</div>	
			</div>	
			<div class="footer-bottom text-center">
			<div class="container">
				<div class="footer-logo">
					<a href="index.html"><span>Re</span>sale</a>
				</div>
				<div class="footer-social-icons">
					<ul>
						<li><a class="facebook" href="#"><span>Facebook</span></a></li>
						<li><a class="twitter" href="#"><span>Twitter</span></a></li>
						<li><a class="flickr" href="#"><span>Flickr</span></a></li>
						<li><a class="googleplus" href="#"><span>Google+</span></a></li>
						<li><a class="dribbble" href="#"><span>Dribbble</span></a></li>
					</ul>
				</div>
				<div class="copyrights">
					<p> © 2016 Resale. All Rights Reserved | Design by  <a href="http://w3layouts.com/"> W3layouts</a></p>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
		</footer>
        <!--footer section end-->
</body>
</html>

product/templates/product/index.html
{% extends 'product/base.html' %}

product/templates/product/product_details.html
{% extends 'product/base.html' %}
{% load static %}

{% block body %}
<div class="container">

    <div class="product-desc">
        <div class="col-md-7 product-view">
            <h2>{{product_details.title}}</h2>
            <p> <i class="glyphicon glyphicon-map-marker"></i><a href="#">Karnataka</a>, <a href="#">Bangalore</a>| Added at {{product_details.created}}, Ad ID: 987654321</p>
            <div class="flexslider">
                <ul class="slides">
                {% for prdimage in product_images %}
                    <li data-thumb="{{prdimage.image.url}}">
                        <img src="{{prdimage.image.url}}" />
                    </li>
                {% endfor %}
                </ul>
            </div>
            <!-- FlexSlider -->
                <script defer src="{% static 'product/js/jquery.flexslider.js' %}"></script>
            <link rel="stylesheet" href="{% static 'product/css/flexslider.css' %}" type="text/css" media="screen" />

                <script>
            // Can also be used with $(document).ready()
            $(window).load(function() {
                $('.flexslider').flexslider({
                animation: "slide",
                controlNav: "thumbnails"
                });
            });
            </script>
            <!-- //FlexSlider -->
            <div class="product-details">
                <h4>Brand : <a href="#">{{product_details.brand}}</a></h4>
                <h4>Views : <strong>150</strong></h4>
                <p><strong>Description </strong>: {{product_details.decrtiption}}</p>    
            </div>
        </div>
        <div class="col-md-5 product-details-grid">
            <div class="item-price">
                <div class="product-price">
                    <p class="p-price">Price</p>
                    <h3 class="rate">Rs. {{product_details.price}}</h3>
                    <div class="clearfix"></div>
                </div>
                <div class="condition">
                    <p class="p-price">Condition</p>
                    <h4>Good</h4>
                    <div class="clearfix"></div>
                </div>
                <div class="itemtype">
                    <p class="p-price">Item Type</p>
                    <h4>Phones</h4>
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="interested text-center">
                <h4>Interested in this Ad?<small> Contact the Seller!</small></h4>
                <p><i class="glyphicon glyphicon-earphone"></i>00-85-9875462655</p>
            </div>
                <div class="tips">
                <h4>Safety Tips for Buyers</h4>
                    <ol>
                        <li><a href="#">Contrary to popular belief.</a></li>
                        <li><a href="#">Contrary to popular belief.</a></li>
                        <li><a href="#">Contrary to popular belief.</a></li>
                        <li><a href="#">Contrary to popular belief.</a></li>
                        <li><a href="#">Contrary to popular belief.</a></li>
                        <li><a href="#">Contrary to popular belief.</a></li>
                        <li><a href="#">Contrary to popular belief.</a></li>
                        <li><a href="#">Contrary to popular belief.</a></li>
                        <li><a href="#">Contrary to popular belief.</a></li>
                    </ol>
                </div>
        </div>
    <div class="clearfix"></div>
</div>
{% endblock body %}

product/templates/product/product_list.html
{% extends 'product/base.html' %}

	
{% block body %}

<div class="container">
    	<div class="ads-grid">
				<div class="side-bar col-md-3">
					<div class="search-hotel">
					<h3 class="sear-head">Name contains</h3>
					<form>
						<input type="text" value="Product name..." onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Product name...';}" required="">
						<input type="submit" value=" ">
					</form>
				</div>
				
				<div class="range">
					<h3 class="sear-head">Price range</h3>
							<ul class="dropdown-menu6">
								<li>
									                
									<div id="slider-range"></div>							
										<input type="text" id="amount" style="border: 0; color: #ffffff; font-weight: normal;" />
									</li>			
							</ul>
							<!---->
							<script type="text/javascript" src="js/jquery-ui.js"></script>
							<script type='text/javascript'>//<![CDATA[ 
							$(window).load(function(){
							 $( "#slider-range" ).slider({
										range: true,
										min: 0,
										max: 9000,
										values: [ 50, 6000 ],
										slide: function( event, ui ) {  $( "#amount" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] );
										}
							 });
							$( "#amount" ).val( "$" + $( "#slider-range" ).slider( "values", 0 ) + " - $" + $( "#slider-range" ).slider( "values", 1 ) );

							});//]]>  

							</script>
							
				</div>
				<div class="featured-ads">
					<h2 class="sear-head fer">Featured Ads</h2>
                    {% for product in product_list %}
					<div class="featured-ad">
						<a href="{% url 'product:product_detail' product.slug %}">
							<div class="featured-ad-left">
								<img src="{{product.image.url}}" title="ad image" alt="" />
							</div>
							<div class="featured-ad-right">
								<h4>{{product.title}}</h4>
								<p>{{product.price}}</p>
							</div>
							<div class="clearfix"></div>
						</a>
					</div>
                    {% endfor %}
					<div class="clearfix"></div>
				</div>
				</div>
				<div class="ads-display col-md-9">
					<div class="wrapper">					
					<div class="bs-example bs-example-tabs" role="tabpanel" data-example-id="togglable-tabs">
					  <ul id="myTab" class="nav nav-tabs nav-tabs-responsive" role="tablist">
						<li role="presentation" class="active">
						  <a href="#home" id="home-tab" role="tab" data-toggle="tab" aria-controls="home" aria-expanded="true">
							<span class="text">All Ads</span>
						  </a>
						</li>
						
					  </ul>
					  <div id="myTabContent" class="tab-content">
						<div role="tabpanel" class="tab-pane fade in active" id="home" aria-labelledby="home-tab">
						   <div>
												<div id="container">
								<div class="view-controls-list" id="viewcontrols">
									<label>view :</label>
									<a class="gridview"><i class="glyphicon glyphicon-th"></i></a>
									<a class="listview active"><i class="glyphicon glyphicon-th-list"></i></a>
								</div>
								<div class="sort">
								   <div class="sort-by">
										<label>Sort By : </label>
										<select>
														<option value="">Most recent</option>
														<option value="">Price: Rs Low to High</option>
														<option value="">Price: Rs High to Low</option>
										</select>
									   </div>
									 </div>
								<div class="clearfix"></div>
							<ul class="list">
                                {% for product in product_list %}
								<a href="{% url 'product:product_detail' product.slug %}">
									<li>
									<img src="{{product.image.url}}" title="" alt="" />
									<section class="list-left">
									<h5 class="title">{{product.title}}</h5>
									<span class="adprice">{{product.price}}</span>
									<p class="catpath">Mobile Phones » Brand</p>
									</section>
									<section class="list-right">
									<span class="date">{{product.created}}</span>
									<span class="cityname">Bangalore, Karnataka</span>
									</section>
									<div class="clearfix"></div>
									</li> 
								</a>
								{% endfor %}
							</ul>
						</div>
							</div>
						</div>
							</div>
						</div>
							</div>
						</div>
					  </div>
					</div>
				</div>
				</div>
				<div class="clearfix"></div>
			</div>
</div>

{% endblock body %}